"""add asset class enum and isin

Revision ID: e90ea3ad86de
Revises: 9223aea760a1
Create Date: 2025-11-21 22:30:16.649471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90ea3ad86de'
down_revision: Union[str, Sequence[str], None] = '9223aea760a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the ENUM type manually first
    assetclass_enum = sa.Enum('EQUITY', 'FIXED_INCOME', 'CASH', 'COMMODITY', 'REAL_ESTATE', 'CRYPTOCURRENCY', 'PRIVATE_EQUITY', 'DERIVATIVE', 'FOREX', 'OTHER', name='assetclass')
    assetclass_enum.create(op.get_bind(), checkfirst=True)

    # Normalize data: Convert existing strings to Uppercase to match Enum values
    op.execute("UPDATE assets SET asset_class = UPPER(asset_class)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('isin', sa.String(length=12), nullable=True))
    op.alter_column('assets', 'asset_class',
               existing_type=sa.VARCHAR(length=50),
               type_=assetclass_enum,
               existing_nullable=False,
               postgresql_using='asset_class::assetclass') # Add explicit cast for PostgreSQL
    op.create_unique_constraint('uq_asset_isin', 'assets', ['isin']) # Added name to constraint
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_isin', 'assets', type_='unique') # Use name here

    # Revert column type
    op.alter_column('assets', 'asset_class',
               existing_type=sa.Enum('EQUITY', 'FIXED_INCOME', 'CASH', 'COMMODITY', 'REAL_ESTATE', 'CRYPTOCURRENCY', 'PRIVATE_EQUITY', 'DERIVATIVE', 'FOREX', 'OTHER', name='assetclass'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='asset_class::text')

    op.drop_column('assets', 'isin')

    # Drop the ENUM type
    assetclass_enum = sa.Enum('EQUITY', 'FIXED_INCOME', 'CASH', 'COMMODITY', 'REAL_ESTATE', 'CRYPTOCURRENCY', 'PRIVATE_EQUITY', 'DERIVATIVE', 'FOREX', 'OTHER', name='assetclass')
    assetclass_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
