from enum import Enum

class AssetClass(str, Enum):
    EQUITY = "EQUITY"
    FIXED_INCOME = "FIXED_INCOME"
    CASH = "CASH"
    COMMODITY = "COMMODITY"
    REAL_ESTATE = "REAL_ESTATE"
    CRYPTOCURRENCY = "CRYPTOCURRENCY"
    PRIVATE_EQUITY = "PRIVATE_EQUITY"
    DERIVATIVE = "DERIVATIVE"
    FOREX = "FOREX"
    OTHER = "OTHER"
